language: java
sudo: false
install: true

addons:
  sonarqube:
    token:
      secure: "439a94dedbca483683cdd65b5fbba5a1388ee1fb"

jdk:
  - oraclejdk8

rvm:
  - 2.2

before_script:
  - gem install awesome_bot

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - awesome_bot **.md       --allow-dupe --allow-redirect --white-list $wl
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
